import Head from "next/head";
import { useRouter } from "next/router";
import styles from "./Layout.module.css";

export default function Layout({ children }) {
  const { query } = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Strike Paywall</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main
        className={styles.main}
        style={
          query?.previewImageUrl
            ? {
                backgroundImage: `url("${query.previewImageUrl}")`,
                backgroundPosition: "center",
                backgroundRepeat: "no-repeat",
              }
            : null
        }
      >
        <div>{children}</div>
      </main>
    </div>
  );
}
