import Head from "next/head";
import { useRouter } from "next/router";
import styles from "./Home.module.css";

export default function Home() {
  const { query } = useRouter();
  const title = query.title ?? "Untitled Paywall";

  return (
    <div className={styles.container}>
      <Head>
        <title>Strike Paywall</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <main className={styles.main}>
        <div>
          <h1>{title}</h1>
        </div>
      </main>
    </div>
  );
}
