import Head from "next/head";
import styles from "./Home.module.css";
import Cta from "./Cta";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Strike Paywall</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main className={styles.main}>
        <Cta />
      </main>
    </div>
  );
}
